### ISSUE TITLE
Get interval until next availability

### ISSUE THREAD

**Issue by hgani** [seanxiesx/redis_rate_limiter#5]
Hi,

I'd like to request a feature to get the interval to the time when the limit will be lifted.

For example, if I set the limit to be 5 every 1 hour. Then if the limit has been hit (the user has performed the action 5 times) and after 15 minutes, the user tries to perform the action again. I'd like to be able to tell the user to wait for 45 minutes.

Thank you

**Comment by seanxiesx** [comment]
does this work? https://github.com/seanxiesx/redis_rate_limiter/pull/6

**Comment by hgani** [comment]
Hi @seanxiesx 

Thanks so much for the quick response.

Yes, that's what I needed and it works well so far. I haven't tested it thoroughly. Will let you know if I encounter any problem later.

**Comment by seanxiesx** [comment]
np. https://rubygems.org/gems/redis_rate_limiter/versions/0.0.9
